### ISSUE TITLE
Add software testing at the last of Linux Setup

### ISSUE THREAD

**Issue by kazunori279** [BrainPad/FindYourCandy#22]
After going through the linux setup, I wasn't sure if I did everything correct. It'd better to have a testing instructions to make sure all the components (opencv, nginx, candy and etc) are installed properly and ready to move to the next step.

**Comment by max-hana** [comment]
Linux setup is quite strait forward in a sense that it is basically a set of install commands. 
(Installing opencv is also self checked along with this instruction.)
we will not make instructions for testing each of OSS components, since they are already documented elsewhere. I'm going to make just links to those.

Currently testing our development is not well documented.
I will raise this as an enhancement, but this will take some time.
If you are in a hurry, please look at the webapp/README.md and robot-arm/README.md.
There are some curl commands at the end that checks some features separately, but it is not described.
(it is probably not hard to guess. i hope.)

**Comment by kazunori279** [comment]
By testing I don't mean a heavy unit test for all the components. I just thought it'd be great to add simple command lines such as "python -V" to check if each important component is installed, such as opencv and gsutil.

**Comment by max-hana** [comment]
- Added some methods for a little testing for gsutil, and python.
- For opencv, added a hint, because its a library.
